apiVersion: apps/v1
kind: Deployment
metadata:
  name: akk-frontend
  labels:
    app: akk-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akk-frontend
  template:
    metadata:
      labels:
        app: akk-frontend
    spec:
      containers:
      - name: frontend
        image: myregistry/akk-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: akk-frontend
spec:
  selector:
    app: akk-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
