name: aml-retrain-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - transformers==4.47.1
      - datasets==2.14.5
      - torch
      - sentencepiece
      - pandas
